# Generated by Django 6.0.4 on 2026-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, default='', help_text="The User's First Name.", max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', help_text="The User's Last Name.", max_length=30, null=True)),
                ('registration_method', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20)),
                ('email', models.EmailField(help_text="The User's Unique Email Address.", max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Indicates whether the User Account is Active')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Indicates whether the User has all Admin Permission')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='The Date and Time when user Joined.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
