"""
Django settings for FakeKilo project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit

try:
    import dj_database_url
except ImportError:  # pragma: no cover - local fallback when optional dependency is absent
    dj_database_url = None
try:
    from decouple import config
except ImportError:  # pragma: no cover - local fallback when optional dependency is absent
    def config(name, default=None, cast=str):
        value = os.environ.get(name, default)
        if value is None:
            return None
        if cast is None:
            return value
        return cast(value)

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - local fallback when optional dependency is absent
    def load_dotenv(_path):
        return False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from the documented repo-root .env first,
# then fall back to the project-local .env used by some existing setups.
for env_file in (BASE_DIR.parent / ".env", BASE_DIR / ".env"):
    load_dotenv(env_file)


DEFAULT_ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
DEFAULT_LOCAL_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]
DEFAULT_PUBLIC_DOMAINS = ["astality.site", "www.astality.site"]
DEFAULT_TRUSTED_ORIGINS = list(DEFAULT_LOCAL_ORIGINS)
TRUTHY_ENV_VALUES = {"1", "true", "t", "yes", "y", "on", "debug", "development", "dev"}
FALSY_ENV_VALUES = {"0", "false", "f", "no", "n", "off", "", "release", "production", "prod"}


def env_flag(name, default=False):
    value = config(name, default=None)
    if value is None:
        return default

    normalized = str(value).strip().lower()
    if normalized in TRUTHY_ENV_VALUES:
        return True
    if normalized in FALSY_ENV_VALUES:
        return False

    return default


def env_list(name, default=None, merge_default=False):
    value = config(name, default="")
    base_values = list(default or [])
    if value is None:
        return base_values

    parsed_values = [item.strip() for item in str(value).split(",") if item.strip()]
    if merge_default:
        merged_values = list(base_values)
        for item in parsed_values:
            extend_unique(merged_values, item)
        return merged_values

    if parsed_values:
        return parsed_values

    return base_values


def env_int(name, default=0):
    return config(name, cast=int, default=default)


def normalize_origin(value):
    item = str(value).strip()
    if not item:
        return None

    parsed = urlsplit(item)
    if not parsed.scheme or not parsed.netloc:
        return None

    return f"{parsed.scheme}://{parsed.netloc}"


def normalize_host(value):
    item = str(value).strip()
    if not item:
        return None

    parsed = urlsplit(item if "://" in item else f"https://{item}")
    return parsed.hostname


def extend_unique(values, candidate):
    if candidate and candidate not in values:
        values.append(candidate)


for public_domain in DEFAULT_PUBLIC_DOMAINS:
    extend_unique(DEFAULT_ALLOWED_HOSTS, public_domain)
    extend_unique(DEFAULT_LOCAL_ORIGINS, f"https://{public_domain}")
    extend_unique(DEFAULT_TRUSTED_ORIGINS, f"https://{public_domain}")


RAILWAY_PUBLIC_DOMAIN = normalize_host(config("RAILWAY_PUBLIC_DOMAIN", default=""))
if RAILWAY_PUBLIC_DOMAIN:
    railway_origin = f"https://{RAILWAY_PUBLIC_DOMAIN}"
    extend_unique(DEFAULT_ALLOWED_HOSTS, RAILWAY_PUBLIC_DOMAIN)
    extend_unique(DEFAULT_LOCAL_ORIGINS, railway_origin)
    extend_unique(DEFAULT_TRUSTED_ORIGINS, railway_origin)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-ka=58p(l+!a#*ose7qj48%^a_ow@tg57h@spukfro7a#@5@+4l",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DEBUG", default=False)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = env_flag("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = env_flag("SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env_flag("CSRF_COOKIE_SECURE", default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env_flag("SECURE_HSTS_PRELOAD", default=True)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default=DEFAULT_ALLOWED_HOSTS,
    merge_default=True,
)
CORS_ALLOWED_ORIGINS = [
    origin
    for origin in (
        normalize_origin(value)
        for value in env_list(
            "CORS_ALLOWED_ORIGINS",
            default=DEFAULT_LOCAL_ORIGINS,
            merge_default=True,
        )
    )
    if origin
]
GOOGLE_OAUTH_ALLOWED_ORIGINS = [
    origin
    for origin in (
        normalize_origin(value)
        for value in env_list(
            "GOOGLE_OAUTH_ALLOWED_ORIGINS",
            default=CORS_ALLOWED_ORIGINS,
            merge_default=True,
        )
    )
    if origin
]
CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in (
        normalize_origin(value)
        for value in env_list(
            "CSRF_TRUSTED_ORIGINS",
            default=DEFAULT_TRUSTED_ORIGINS,
            merge_default=True,
        )
    )
    if origin
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Core',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'Core.middleware.DevCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FakeKilo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FakeKilo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASE_URL = str(config("DATABASE_URL", default="")).strip()
if DATABASE_URL and dj_database_url is not None:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=env_int("DATABASE_CONN_MAX_AGE", default=600),
            ssl_require=env_flag("DATABASE_SSL_REQUIRE", default=True),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'Core' / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
STORAGES = {
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}
# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'Core.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'Core.authentication.PasswordBoundJWTAuthentication',
    ]
}

GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='')
GOOGLE_OAUTH_CLIENT_SECRET = config(
    'GOOGLE_OAUTH_CLIENT_SECRET',
    default=config('GOOGLE_OAUTH_CLIENT_SECET', default='')
)
GOOGLE_OAUTH_CLIENT_SECET = GOOGLE_OAUTH_CLIENT_SECRET

APP_NAME = config("APP_NAME", default="FakeKilo")
EMAIL_DELIVERY_MODE = config("EMAIL_DELIVERY_MODE", default="auto")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env_flag("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_flag("EMAIL_USE_SSL", default=False)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", cast=int, default=10)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
EMAIL_REPLY_TO = config("EMAIL_REPLY_TO", default="")
RESEND_API_URL = config("RESEND_API_URL", default="https://api.resend.com")
RESEND_API_KEY = config("RESEND_API_KEY", default="")
RESEND_FROM_EMAIL = config("RESEND_FROM_EMAIL", default="")
RESEND_REPLY_TO = config("RESEND_REPLY_TO", default=RESEND_FROM_EMAIL)
RESEND_REQUEST_TIMEOUT_SECONDS = config(
    "RESEND_REQUEST_TIMEOUT_SECONDS",
    cast=int,
    default=10,
)
SIGNUP_OTP_LENGTH = config("SIGNUP_OTP_LENGTH", cast=int, default=6)
SIGNUP_OTP_EXPIRY_MINUTES = config("SIGNUP_OTP_EXPIRY_MINUTES", cast=int, default=10)
SIGNUP_OTP_RESEND_COOLDOWN_SECONDS = config(
    "SIGNUP_OTP_RESEND_COOLDOWN_SECONDS",
    cast=int,
    default=60,
)
SIGNUP_OTP_MAX_ATTEMPTS = config(
    "SIGNUP_OTP_MAX_ATTEMPTS",
    cast=int,
    default=5,
)
PASSWORD_RESET_TIMEOUT = config("PASSWORD_RESET_TIMEOUT", cast=int, default=3600)
PASSWORD_RESET_REQUEST_COOLDOWN_SECONDS = config(
    "PASSWORD_RESET_REQUEST_COOLDOWN_SECONDS",
    cast=int,
    default=60,
)
