"""
Django settings for FakeKilo project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
DEFAULT_LOCAL_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]
TRUTHY_ENV_VALUES = {"1", "true", "t", "yes", "y", "on", "debug", "development", "dev"}
FALSY_ENV_VALUES = {"0", "false", "f", "no", "n", "off", "", "release", "production", "prod"}


def env_flag(name, default=False):
    value = config(name, default=None)
    if value is None:
        return default

    normalized = str(value).strip().lower()
    if normalized in TRUTHY_ENV_VALUES:
        return True
    if normalized in FALSY_ENV_VALUES:
        return False

    return default


def env_list(name, default=None):
    value = config(name, default="")
    if value is None:
        return list(default or [])

    parsed_values = [item.strip() for item in str(value).split(",") if item.strip()]
    if parsed_values:
        return parsed_values

    return list(default or [])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-ka=58p(l+!a#*ose7qj48%^a_ow@tg57h@spukfro7a#@5@+4l",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DEBUG", default=False)

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = env_flag("SECURE_SSL_REDIRECT", default=True)
    SESSION_COOKIE_SECURE = env_flag("SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env_flag("CSRF_COOKIE_SECURE", default=True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
    }
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = env_flag("SECURE_HSTS_SECONDS", default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env_flag("SECURE_HSTS_PRELOAD", default=True)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=DEFAULT_ALLOWED_HOSTS)
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", default=DEFAULT_LOCAL_ORIGINS)
GOOGLE_OAUTH_ALLOWED_ORIGINS = env_list(
    "GOOGLE_OAUTH_ALLOWED_ORIGINS",
    default=CORS_ALLOWED_ORIGINS,
)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Core',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'Core.middleware.DevCorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FakeKilo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FakeKilo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'Core.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = config(
    'GOOGLE_OAUTH_CLIENT_SECRET',
    default=config('GOOGLE_OAUTH_CLIENT_SECET', default='')
)
GOOGLE_OAUTH_CLIENT_SECET = GOOGLE_OAUTH_CLIENT_SECRET

APP_NAME = config("APP_NAME", default="FakeKilo")
EMAIL_DELIVERY_MODE = config("EMAIL_DELIVERY_MODE", default="auto")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env_flag("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_flag("EMAIL_USE_SSL", default=False)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", cast=int, default=10)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
EMAIL_REPLY_TO = config("EMAIL_REPLY_TO", default="")
RESEND_API_URL = config("RESEND_API_URL", default="https://api.resend.com")
RESEND_API_KEY = config("RESEND_API_KEY", default="")
RESEND_FROM_EMAIL = config("RESEND_FROM_EMAIL", default="")
RESEND_REPLY_TO = config("RESEND_REPLY_TO", default=RESEND_FROM_EMAIL)
RESEND_REQUEST_TIMEOUT_SECONDS = config(
    "RESEND_REQUEST_TIMEOUT_SECONDS",
    cast=int,
    default=10,
)
SIGNUP_OTP_LENGTH = config("SIGNUP_OTP_LENGTH", cast=int, default=6)
SIGNUP_OTP_EXPIRY_MINUTES = config("SIGNUP_OTP_EXPIRY_MINUTES", cast=int, default=10)
SIGNUP_OTP_RESEND_COOLDOWN_SECONDS = config(
    "SIGNUP_OTP_RESEND_COOLDOWN_SECONDS",
    cast=int,
    default=60,
)
SIGNUP_OTP_MAX_ATTEMPTS = config(
    "SIGNUP_OTP_MAX_ATTEMPTS",
    cast=int,
    default=5,
)
